Feature/fp
schleupen/as4-connect-business-api-adapter pull request #2
Opened 2024-08-19 08:20 UTC by jbr-Schleupen

2024-08-19 09:15 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +	public sealed class FpMessageReceiver(
Habe keine Tests für den FpMessageReceiver gefunden?

2024-08-23 12:34 UTC, aer-schleupen commented on README.md
doku fehlt

2024-08-23 12:36 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/ReceiveStatus.cs
> +    private readonly Dictionary<string, Tuple<InboxFpMessage, Exception>> failedReceivedMessages = new();
unused?

2024-08-23 12:36 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/ReceiveStatus.cs
> +    public void AddFailure(int failedMessageCount)
missing details

2024-08-23 12:37 UTC, aer-schleupen commented on BusinessAdapter.FP.UnitTests/Receiving/FpMessageReceiverTests.cs
> +    public class FpMessageReceiverTests
Missing testcases

2024-08-23 12:41 UTC, aer-schleupen commented on BusinessAdapter.FP/Configuration/Validation/EICMappingOptionsValidator.cs
> +	}
add Validation for EIC Mapping

2024-08-23 12:48 UTC, aer-schleupen commented on BusinessAdapter.FP/Configuration/EICMappingEntry.cs
> +{
Was ist MpType was ist FpType? MpTyp ist die vergebene Stelle der Codenummer (Dictionary-Key).  
Irgendwie wirkt das inkonsistent, weil Bilanzkreis ausgeschrieben und deutsch ist. Der Rest ist abgekürzt.

2024-08-23 12:51 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/As4FpMessage.cs
> +        BdewFulfillmentDate = bdewFulfillmentDate;
Warum nutzen wir hier nicht 'FpBDEWProperties' ?

2024-08-23 12:52 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/As4FpMessage.cs
> +    public As4FpMessage(
Naming: FpInboxMessage?

2024-08-23 12:54 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/MessageReceiveInfo.cs
> +{
Naming der Felder, Methoden wäre besser angelegt an das Statusmodell in der B-Api: Provided, Acknowledged

2024-08-23 13:01 UTC, aer-schleupen commented on BusinessAdapter.FP/Gateways/IBusinessApiGateway.cs
> +		Task<BusinessApiResponse<bool>> AcknowledgeReceivedMessageAsync(InboxFpMessage mpMessage);
naming: mpMessage

2024-08-23 13:02 UTC, aer-schleupen commented on BusinessAdapter.FP/Gateways/IBusinessApiGateway.cs
> +		Task<BusinessApiResponse<InboxFpMessage>> ReceiveMessageAsync(As4FpMessage mpMessage);
müsste hier nicht 'MessageReceiveInfo' von QueryAvailableMessagesAsync reingegeben werden?

2024-08-23 13:04 UTC, aer-schleupen commented on BusinessAdapter.FP.UnitTests/Parsing/FpFileParserTests.cs
> +    // TODO Unhappy paths are untested (missing values)...
// TODO Unhappy paths are untested (missing values)...

2024-08-23 13:06 UTC, aer-schleupen commented on BusinessAdapter.FP.UnitTests/Parsing/FpFileParserTests.Fixture.cs
> +            return dir + "/../../../Parsing/20240125_PPS_0X1001A1001A264_FINGRID_002_ANO_2024-01-26T08-2344Z.xml";
validate DRY [line:30,24,13]
use Path.Combine

2024-08-23 13:09 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +					exceptions = await QueryMessagesAsync(receiverIdentificationNumber,
strange signature QueryMessageAsync return List<Exceptions> ?

2024-08-23 13:11 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +			int successfulMessageCount = 0;
better use StatusObject ( s. SendStatus )

2024-08-23 13:12 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +		public async Task<ReceiveStatus> ReceiveAvailableMessagesAsync(CancellationToken cancellationToken)
Method too long

2024-08-23 13:14 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +	public sealed class FpMessageReceiver(
the code in here doesn't look so nice :(

2024-08-23 13:16 UTC, aer-schleupen requested changes
see feedback

2024-08-23 13:17 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +		IOptions<ReceiveOptions> receiveOptions,
the code in here doesn't look so nice :(

2024-08-23 14:03 UTC, jbr-Schleupen commented on BusinessAdapter.FP.UnitTests/Parsing/FpFileParserTests.cs
> +    // TODO Unhappy paths are untested (missing values)...
Solange wir keine Beispiel files haben, wird es auch so bleiben.

2024-08-28 08:37 UTC, aer-schleupen commented on BusinessAdapter.FP/Configuration/EICMappingEntry.cs
> +    public string Bilanzkreis { get; set; }
inconsistent with property 'TypeHaendlerfahrplan' in record FpFileName

2024-08-28 08:39 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/ReceiveStatus.cs
> +    public int SuccessfulMessages => _successfulMessages.Count;
instance field naming should be without underscore

2024-08-28 08:50 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +                as4BusinessApiClient.Value.Dispose();
wrong place - assuming we remove the logging, then we also remove the disposing?

2024-08-28 08:51 UTC, aer-schleupen commented on BusinessAdapter.FP/Receiving/FpMessageReceiver.cs
> +            var totalNumberOfMessages = as4BusinessApiClients.Keys.Sum(x => x.GetAvailableMessages().Length);
can we shift this logic out of the Receiver into the status object?

2024-08-28 08:59 UTC, aer-schleupen commented on BusinessAdapter.FP.UnitTests/Receiving/FpMessageReceiverTests.cs
> +
we only have test cases for error situations. Missing testcase ...
- check if ReceiveStatus is correclty if all messages are successful received
- check if ReceiveStatus is correclty if some messages received correctly and some are received with failures -> that should not block new message stream
- ...

2024-09-03 08:29 UTC, merged